"""Canonical Deeper Notebook product identity."""

PRODUCT_NAME = "Deeper Notebook"
PRODUCT_SLUG = "deeper-notebook"
TAGLINE = "Think further with every source"
REPOSITORY_OWNER = "Antman1526"
REPOSITORY_NAME = "Deeper-Notebook"
REPOSITORY = f"{REPOSITORY_OWNER}/{REPOSITORY_NAME}"
REPOSITORY_URL = f"https://github.com/{REPOSITORY}"
DATA_DIR_NAME = ".deeper-notebook"
LEGACY_DATA_DIR_NAME = ".open-notebook-plus"
API_NAMESPACE = "/api/deeper-notebook"
LEGACY_API_NAMESPACE = "/api/onp"
PYTHON_DISTRIBUTION = "deeper-notebook"
PYTHON_PACKAGE = "deeper_notebook"
LEGACY_PYTHON_PACKAGE = "open_notebook"
MAC_APP_NAME = "Deeper Notebook.app"
WINDOWS_EXE_NAME = "Deeper Notebook.exe"
WINDOWS_INSTALLER_NAME = "Deeper-Notebook-Setup-x64.exe"
