from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from desktop.window import _THEMES

CSS_PATHS = (
    ROOT / "desktop/first_run/static/themes.css",
    ROOT / "desktop/model_manager/static/themes.css",
    ROOT / "desktop/memory_dashboard/static/themes.css",
)
CATALOG_PATH = ROOT / "desktop/first_run/static/theme-catalog.generated.js"
THEME_META = {
    "research-core-dark": ("Research Core Dark", "featured"),
    "research-core-light": ("Research Core Light", "featured"),
    "deep-ocean": ("Deep Ocean", "dark"),
    "graphite-lab": ("Graphite Lab", "dark"),
    "arctic-research": ("Arctic Research", "light"),
    "archive-paper": ("Archive Paper", "light"),
    "high-contrast-dark": ("High Contrast Dark", "accessibility"),
    "high-contrast-light": ("High Contrast Light", "accessibility"),
    "light-blue": ("Light Blue", "classics"),
    "system": ("System", "classics"),
    "solarized-light": ("Solarized Light", "light"),
    "github-light": ("GitHub Light", "light"),
    "paper": ("Paper", "light"),
    "catppuccin-latte": ("Catppuccin Latte", "light"),
    "rose-pine-dawn": ("Rosé Pine Dawn", "light"),
    "dark": ("Dark", "classics"),
    "midnight-aurora": ("Midnight Aurora", "classics"),
    "tokyo-night": ("Tokyo Night", "dark"),
    "catppuccin-mocha": ("Catppuccin Mocha", "dark"),
    "rose-pine": ("Rosé Pine", "dark"),
    "one-dark": ("One Dark", "dark"),
    "gruvbox-dark": ("Gruvbox Dark", "dark"),
    "solarized-dark": ("Solarized Dark", "dark"),
    "dracula": ("Dracula", "dark"),
    "nord": ("Nord", "dark"),
}


def render_css() -> str:
    blocks = ["/* Generated by scripts/render_theme_static_assets.py. */"]
    for theme_id, palette in _THEMES.items():
        blocks.append(
            f'[data-theme="{theme_id}"] {{\n'
            f'  --bg: {palette["bg"]};\n'
            f'  --surface: {palette["card"]};\n'
            f'  --text: {palette["fg"]};\n'
            f'  --muted: {palette["muted_fg"]};\n'
            f'  --border: {palette["border"]};\n'
            f'  --primary: {palette["primary"]};\n'
            f'  --accent: {palette["accent"]};\n'
            f'  --on-primary: {palette["primary_fg"]};\n'
            '}\n'
        )
    return "\n".join(blocks).rstrip("\n") + "\n"


def render_catalog() -> str:
    assert set(THEME_META) == set(_THEMES)
    entries = []
    for theme_id, palette in _THEMES.items():
        label, group = THEME_META[theme_id]
        entries.append({
            "id": theme_id,
            "name": label,
            "group": group,
            "dark": bool(palette["is_dark"]),
            "bg": palette["bg"],
            "fg": palette["primary"],
        })
    payload = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    return f"window.DN_THEME_CATALOG = {payload};\n"


def render_assets(*, check: bool = False) -> int:
    expected = {path: render_css() for path in CSS_PATHS}
    expected[CATALOG_PATH] = render_catalog()
    if check:
        stale = [
            path for path, content in expected.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        return 1 if stale else 0
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(render_assets(check="--check" in sys.argv))
